### ISSUE TITLE
Kuru disease persists - Intent to get rid of the mechanic fully

### ISSUE THREAD

**Issue by ComradeSythar** [HebiKotei/DecayRP#1]
Kuru still can be contracted after eating human meat (dropped by the red hood zombie guy).  I have not tested same meat obtained from other sources such as other players.

I have tried consumption of dried and cooked "meat" and they both seem to cause kuru. I had not tried raw meat, but I don't see why a different result would be achieved.

**Comment by YvanCywan** [comment]
Please ensure the template is in use, it is in the text box when creating the issue itself.

We were aware of the issue, the server has been flipped between the official mod (which did disable kuru) and the development mod (which did not until today), this may have been solved now. The database has been wiped and encourage you to test it again in order to ensure that it is functioning.

**Comment by YvanCywan** [comment]
With no update on this ticket, and some asking around, it seems as if kuru is not enabled anymore.
I will now close this issue and mark it as complete. If there are any issues relating to this, please notify us and we will reopen this issue.
